/**
 * src/discord/role-sync.js
 * Synchronizes Discord Roles based on Riot Games Ranked Tiers.
 */
const fs = require('fs');

// --- 1. CONFIGURATION & SECRETS ---
const DISCORD_TOKEN = process.env.DISCORD_BOT_TOKEN;
const GUILD_ID = process.env.DISCORD_GUILD_ID;

if (!DISCORD_TOKEN || !GUILD_ID) {
    console.error("❌ CRITICAL: Discord Token or Guild ID is missing from .env");
    process.exit(1);
}

// ⚠️ REPLACE THESE WITH YOUR ACTUAL DISCORD ROLE IDs (Right-click role -> Copy ID)
// MUST BE STRINGS!
const RANK_ROLES = {
    "CHALLENGER": "1358901521990942771",
    "GRANDMASTER": "1358901520887713883",
    "MASTER": "1358901519566504068",
    "DIAMOND": "1358901518820053204",
    "EMERALD": "1358901517964284015",
    "PLATINUM": "1358901517028954413",
    "GOLD": "1358901516118786108",
    "SILVER": "1358901515099701289",
    "BRONZE": "1358901513942204416",
    "IRON": "1358901512994164978",
    "UNRANKED": "1504828753459675166" 
};

// We need a list of ALL rank roles so we can strip the old ones.
const ALL_RANK_ROLE_IDS = Object.values(RANK_ROLES);

const sleep = ms => new Promise(r => setTimeout(r, ms));

// --- 2. BULLETPROOF DISCORD API WRAPPER ---
async function discordFetch(endpoint, method = 'GET', body = null) {
    const url = `https://discord.com/api/v10${endpoint}`;
    const options = {
        method,
        headers: {
            'Authorization': `Bot ${DISCORD_TOKEN}`,
            'Content-Type': 'application/json',
            'User-Agent': 'UIC-Analytics-Bot (https://github.com/uic, 1.0.0)'
        }
    };
    if (body) options.body = JSON.stringify(body);

    const res = await fetch(url, options);

    // Handle Discord Rate Limits (429)
    if (res.status === 429) {
        const data = await res.json();
        const delay = (data.retry_after * 1000) + 100; // Add 100ms safety buffer
        console.warn(`⚠️ [Discord] Rate limited. Sleeping for ${delay}ms...`);
        await sleep(delay);
        return discordFetch(endpoint, method, body);
    }

    if (!res.ok) {
        if (res.status === 404) throw new Error("404_UNKNOWN_MEMBER");
        if (res.status === 403) throw new Error("403_FORBIDDEN_HIERARCHY");
        throw new Error(`Discord API Error ${res.status}: ${res.statusText}`);
    }

    // DELETE and PUT requests to Discord usually return 204 No Content (empty body)
    return res.status === 204 ? true : await res.json();
}

// --- 3. THE CORE SYNC LOGIC ---
async function syncPlayerRole(discordId, riotTier, gameName) {
    if (!discordId || discordId === "") return;

    // Default to Unranked if Riot API returned null/undefined
    const targetTier = riotTier ? riotTier.toUpperCase() : "UNRANKED";
    const targetRoleId = RANK_ROLES[targetTier];

    if (!targetRoleId) {
        console.warn(`⚠️ [Skip] ${gameName}: Unknown Tier '${targetTier}'`);
        return;
    }

    try {
        // Step 1: Get user's current roles
        const memberData = await discordFetch(`/guilds/${GUILD_ID}/members/${discordId}`);
        const currentRoles = memberData.roles;

        // Step 2: Calculate the Diff
        const hasTargetRole = currentRoles.includes(targetRoleId);
        const wrongRankRoles = currentRoles.filter(id => ALL_RANK_ROLE_IDS.includes(id) && id !== targetRoleId);

        if (hasTargetRole && wrongRankRoles.length === 0) {
            console.log(`✅ [OK] ${gameName} is already synced to ${targetTier}.`);
            return;
        }

        // Step 3: Add the correct role
        if (!hasTargetRole) {
            await discordFetch(`/guilds/${GUILD_ID}/members/${discordId}/roles/${targetRoleId}`, 'PUT');
            console.log(`🆙 [Updated] ${gameName}: Granted ${targetTier} role.`);
            await sleep(500); // 500ms safety pacer
        }

        // Step 4: Strip the incorrect/old roles
        for (const badRoleId of wrongRankRoles) {
            await discordFetch(`/guilds/${GUILD_ID}/members/${discordId}/roles/${badRoleId}`, 'DELETE');
            console.log(`🧹 [Cleaned] ${gameName}: Removed outdated rank role.`);
            await sleep(500); // 500ms safety pacer
        }

    } catch (e) {
        if (e.message === "404_UNKNOWN_MEMBER") {
            console.log(`👻 [Ghost] ${gameName} (ID: ${discordId}) is not in the Discord server.`);
        } else if (e.message === "403_FORBIDDEN_HIERARCHY") {
            console.error(`🚨 [Permission Error] Cannot assign role to ${gameName}. Move the Bot's role HIGHER in Server Settings!`);
        } else {
            console.error(`❌ [Error] Failed to sync ${gameName}:`, e.message);
        }
    }
}

// --- 4. EXECUTION FLOW ---
async function run() {
    console.log("🚀 Starting Discord Role Sync...");

    // Read the data generated by your Riot Analytics engine
    // (Adjust the path if your engine saves it differently)
    const dataPath = './data/player_state.json'; 
    if (!fs.existsSync(dataPath)) {
        console.error("❌ No player data found. Did the Riot Engine run first?");
        process.exit(1);
    }

    const db = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));

    // Loop through the data and sync
    for (const [teamName, teamData] of Object.entries(db)) {
        for (const player of teamData.roster) {
            // We only process if they have a Discord ID and are actively tracked
            if (player.trackStats && player.discordId) {
                // Assuming your Riot script saves the tier here (e.g., player.tier = "DIAMOND")
                await syncPlayerRole(player.discordId, player.tier, player.gameName);
                await sleep(1000); // 1 Second global pacer between users to guarantee zero 429s
            }
        }
    }

    console.log("🎉 Discord Role Sync Complete!");
}

run();
